
#Sort, filters and pagination:
#use GetAll methods with Query Params:
#?sort_by=fieldName
#?sort_order=order (asc is default)
#?filter=fieldName1 %3A argument1 %2C argument2 %7C fieldName2%3Aargument1%2Crgument2
#?limit=limitNum&page=PageNum

#You can use all or only one and dont use any of query params. Example:
#GET articles?sort_by=edition_date&oreder_by=desc&filter=difficulty%3Amiddle%2Ajunior&limit=5&page=1

GET http://localhost:1000/articles?limit=10&page=1
Content-Type: application/json

### Get audios
GET http://localhost:1000/audios?sort_by=uuid&sort_order=desc&limit=5&page=2
Content-Type: application/json

// SQL injectiom detection
### Get videos
GET http://localhost:1000/videos?filter=ALTER%20table%3Amiddle
Content-Type: application/json

### Get books
GET http://localhost:1000/books?limit=5&page=2
Content-Type: application/json

// remove composites

// query refactor    CREATE (look at book create Storage), UPDATE ?
// tests

// solve problem with tag validation while creating books/auido/video/article in DB query any/in (tags)

// video save/update/load file functions were disabled