// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	image "image"
	io "io"
	domain "library-go/internal/domain"
	utils "library-go/pkg/utils"
	reflect "reflect"
)

// MockArticleService is a mock of ArticleService interface
type MockArticleService struct {
	ctrl     *gomock.Controller
	recorder *MockArticleServiceMockRecorder
}

// MockArticleServiceMockRecorder is the mock recorder for MockArticleService
type MockArticleServiceMockRecorder struct {
	mock *MockArticleService
}

// NewMockArticleService creates a new mock instance
func NewMockArticleService(ctrl *gomock.Controller) *MockArticleService {
	mock := &MockArticleService{ctrl: ctrl}
	mock.recorder = &MockArticleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockArticleService) EXPECT() *MockArticleServiceMockRecorder {
	return m.recorder
}

// GetByUUID mocks base method
func (m *MockArticleService) GetByUUID(UUID string) (*domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", UUID)
	ret0, _ := ret[0].(*domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID
func (mr *MockArticleServiceMockRecorder) GetByUUID(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockArticleService)(nil).GetByUUID), UUID)
}

// GetAll mocks base method
func (m *MockArticleService) GetAll(sortingOptions *domain.SortFilterPagination) ([]*domain.Article, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", sortingOptions)
	ret0, _ := ret[0].([]*domain.Article)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll
func (mr *MockArticleServiceMockRecorder) GetAll(sortingOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockArticleService)(nil).GetAll), sortingOptions)
}

// Delete mocks base method
func (m *MockArticleService) Delete(UUID, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", UUID, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockArticleServiceMockRecorder) Delete(UUID, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArticleService)(nil).Delete), UUID, path)
}

// Create mocks base method
func (m *MockArticleService) Create(article *domain.CreateArticleDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", article)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockArticleServiceMockRecorder) Create(article interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockArticleService)(nil).Create), article)
}

// Update mocks base method
func (m *MockArticleService) Update(article *domain.UpdateArticleDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", article)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockArticleServiceMockRecorder) Update(article interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockArticleService)(nil).Update), article)
}

// LoadFile mocks base method
func (m *MockArticleService) LoadFile(path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFile", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadFile indicates an expected call of LoadFile
func (mr *MockArticleServiceMockRecorder) LoadFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFile", reflect.TypeOf((*MockArticleService)(nil).LoadFile), path)
}

// SaveFile mocks base method
func (m *MockArticleService) SaveFile(path, fileName string, file io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", path, fileName, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFile indicates an expected call of SaveFile
func (mr *MockArticleServiceMockRecorder) SaveFile(path, fileName, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockArticleService)(nil).SaveFile), path, fileName, file)
}

// UpdateFile mocks base method
func (m *MockArticleService) UpdateFile(dto *domain.UpdateArticleFileDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFile", dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFile indicates an expected call of UpdateFile
func (mr *MockArticleServiceMockRecorder) UpdateFile(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockArticleService)(nil).UpdateFile), dto)
}

// LoadImage mocks base method
func (m *MockArticleService) LoadImage(path string, format utils.Format, extension utils.Extension) (*image.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadImage", path, format, extension)
	ret0, _ := ret[0].(*image.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadImage indicates an expected call of LoadImage
func (mr *MockArticleServiceMockRecorder) LoadImage(path, format, extension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadImage", reflect.TypeOf((*MockArticleService)(nil).LoadImage), path, format, extension)
}

// SaveImage mocks base method
func (m *MockArticleService) SaveImage(path string, image *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveImage", path, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveImage indicates an expected call of SaveImage
func (mr *MockArticleServiceMockRecorder) SaveImage(path, image interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveImage", reflect.TypeOf((*MockArticleService)(nil).SaveImage), path, image)
}

// UpdateImage mocks base method
func (m *MockArticleService) UpdateImage(path string, image *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImage", path, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateImage indicates an expected call of UpdateImage
func (mr *MockArticleServiceMockRecorder) UpdateImage(path, image interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImage", reflect.TypeOf((*MockArticleService)(nil).UpdateImage), path, image)
}

// Rate mocks base method
func (m *MockArticleService) Rate(UUID string, rating float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rate", UUID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rate indicates an expected call of Rate
func (mr *MockArticleServiceMockRecorder) Rate(UUID, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rate", reflect.TypeOf((*MockArticleService)(nil).Rate), UUID, rating)
}

// DownloadCountUp mocks base method
func (m *MockArticleService) DownloadCountUp(UUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadCountUp", UUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadCountUp indicates an expected call of DownloadCountUp
func (mr *MockArticleServiceMockRecorder) DownloadCountUp(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadCountUp", reflect.TypeOf((*MockArticleService)(nil).DownloadCountUp), UUID)
}

// MockAudioService is a mock of AudioService interface
type MockAudioService struct {
	ctrl     *gomock.Controller
	recorder *MockAudioServiceMockRecorder
}

// MockAudioServiceMockRecorder is the mock recorder for MockAudioService
type MockAudioServiceMockRecorder struct {
	mock *MockAudioService
}

// NewMockAudioService creates a new mock instance
func NewMockAudioService(ctrl *gomock.Controller) *MockAudioService {
	mock := &MockAudioService{ctrl: ctrl}
	mock.recorder = &MockAudioServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAudioService) EXPECT() *MockAudioServiceMockRecorder {
	return m.recorder
}

// GetByUUID mocks base method
func (m *MockAudioService) GetByUUID(UUID string) (*domain.Audio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", UUID)
	ret0, _ := ret[0].(*domain.Audio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID
func (mr *MockAudioServiceMockRecorder) GetByUUID(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockAudioService)(nil).GetByUUID), UUID)
}

// GetAll mocks base method
func (m *MockAudioService) GetAll(sortingOptions *domain.SortFilterPagination) ([]*domain.Audio, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", sortingOptions)
	ret0, _ := ret[0].([]*domain.Audio)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll
func (mr *MockAudioServiceMockRecorder) GetAll(sortingOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAudioService)(nil).GetAll), sortingOptions)
}

// Delete mocks base method
func (m *MockAudioService) Delete(UUID, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", UUID, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockAudioServiceMockRecorder) Delete(UUID, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAudioService)(nil).Delete), UUID, path)
}

// Create mocks base method
func (m *MockAudioService) Create(audio *domain.CreateAudioDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", audio)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockAudioServiceMockRecorder) Create(audio interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAudioService)(nil).Create), audio)
}

// Update mocks base method
func (m *MockAudioService) Update(audio *domain.UpdateAudioDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", audio)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockAudioServiceMockRecorder) Update(audio interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAudioService)(nil).Update), audio)
}

// LoadFile mocks base method
func (m *MockAudioService) LoadFile(path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFile", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadFile indicates an expected call of LoadFile
func (mr *MockAudioServiceMockRecorder) LoadFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFile", reflect.TypeOf((*MockAudioService)(nil).LoadFile), path)
}

// SaveFile mocks base method
func (m *MockAudioService) SaveFile(path, fileName string, file io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", path, fileName, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFile indicates an expected call of SaveFile
func (mr *MockAudioServiceMockRecorder) SaveFile(path, fileName, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockAudioService)(nil).SaveFile), path, fileName, file)
}

// UpdateFile mocks base method
func (m *MockAudioService) UpdateFile(dto *domain.UpdateAudioFileDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFile", dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFile indicates an expected call of UpdateFile
func (mr *MockAudioServiceMockRecorder) UpdateFile(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockAudioService)(nil).UpdateFile), dto)
}

// Rate mocks base method
func (m *MockAudioService) Rate(UUID string, rating float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rate", UUID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rate indicates an expected call of Rate
func (mr *MockAudioServiceMockRecorder) Rate(UUID, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rate", reflect.TypeOf((*MockAudioService)(nil).Rate), UUID, rating)
}

// DownloadCountUp mocks base method
func (m *MockAudioService) DownloadCountUp(UUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadCountUp", UUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadCountUp indicates an expected call of DownloadCountUp
func (mr *MockAudioServiceMockRecorder) DownloadCountUp(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadCountUp", reflect.TypeOf((*MockAudioService)(nil).DownloadCountUp), UUID)
}

// MockAuthorService is a mock of AuthorService interface
type MockAuthorService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorServiceMockRecorder
}

// MockAuthorServiceMockRecorder is the mock recorder for MockAuthorService
type MockAuthorServiceMockRecorder struct {
	mock *MockAuthorService
}

// NewMockAuthorService creates a new mock instance
func NewMockAuthorService(ctrl *gomock.Controller) *MockAuthorService {
	mock := &MockAuthorService{ctrl: ctrl}
	mock.recorder = &MockAuthorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthorService) EXPECT() *MockAuthorServiceMockRecorder {
	return m.recorder
}

// GetByUUID mocks base method
func (m *MockAuthorService) GetByUUID(UUID string) (*domain.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", UUID)
	ret0, _ := ret[0].(*domain.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID
func (mr *MockAuthorServiceMockRecorder) GetByUUID(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockAuthorService)(nil).GetByUUID), UUID)
}

// GetAll mocks base method
func (m *MockAuthorService) GetAll(limit, offset int) ([]*domain.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, offset)
	ret0, _ := ret[0].([]*domain.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockAuthorServiceMockRecorder) GetAll(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAuthorService)(nil).GetAll), limit, offset)
}

// Delete mocks base method
func (m *MockAuthorService) Delete(UUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", UUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockAuthorServiceMockRecorder) Delete(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuthorService)(nil).Delete), UUID)
}

// Create mocks base method
func (m *MockAuthorService) Create(author *domain.CreateAuthorDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", author)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockAuthorServiceMockRecorder) Create(author interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthorService)(nil).Create), author)
}

// Update mocks base method
func (m *MockAuthorService) Update(author *domain.UpdateAuthorDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", author)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockAuthorServiceMockRecorder) Update(author interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuthorService)(nil).Update), author)
}

// MockBookService is a mock of BookService interface
type MockBookService struct {
	ctrl     *gomock.Controller
	recorder *MockBookServiceMockRecorder
}

// MockBookServiceMockRecorder is the mock recorder for MockBookService
type MockBookServiceMockRecorder struct {
	mock *MockBookService
}

// NewMockBookService creates a new mock instance
func NewMockBookService(ctrl *gomock.Controller) *MockBookService {
	mock := &MockBookService{ctrl: ctrl}
	mock.recorder = &MockBookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBookService) EXPECT() *MockBookServiceMockRecorder {
	return m.recorder
}

// GetByUUID mocks base method
func (m *MockBookService) GetByUUID(UUID string) (*domain.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", UUID)
	ret0, _ := ret[0].(*domain.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID
func (mr *MockBookServiceMockRecorder) GetByUUID(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockBookService)(nil).GetByUUID), UUID)
}

// GetAll mocks base method
func (m *MockBookService) GetAll(sortingOptions *domain.SortFilterPagination) ([]*domain.Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", sortingOptions)
	ret0, _ := ret[0].([]*domain.Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll
func (mr *MockBookServiceMockRecorder) GetAll(sortingOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockBookService)(nil).GetAll), sortingOptions)
}

// Delete mocks base method
func (m *MockBookService) Delete(UUID, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", UUID, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockBookServiceMockRecorder) Delete(UUID, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBookService)(nil).Delete), UUID, path)
}

// Create mocks base method
func (m *MockBookService) Create(book *domain.CreateBookDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", book)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockBookServiceMockRecorder) Create(book interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookService)(nil).Create), book)
}

// Update mocks base method
func (m *MockBookService) Update(book *domain.UpdateBookDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", book)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockBookServiceMockRecorder) Update(book interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBookService)(nil).Update), book)
}

// LoadFile mocks base method
func (m *MockBookService) LoadFile(path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFile", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadFile indicates an expected call of LoadFile
func (mr *MockBookServiceMockRecorder) LoadFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFile", reflect.TypeOf((*MockBookService)(nil).LoadFile), path)
}

// SaveFile mocks base method
func (m *MockBookService) SaveFile(path, fileName string, file io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", path, fileName, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFile indicates an expected call of SaveFile
func (mr *MockBookServiceMockRecorder) SaveFile(path, fileName, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockBookService)(nil).SaveFile), path, fileName, file)
}

// UpdateFile mocks base method
func (m *MockBookService) UpdateFile(dto *domain.UpdateBookFileDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFile", dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFile indicates an expected call of UpdateFile
func (mr *MockBookServiceMockRecorder) UpdateFile(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockBookService)(nil).UpdateFile), dto)
}

// LoadImage mocks base method
func (m *MockBookService) LoadImage(path string, format utils.Format, extension utils.Extension) (*image.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadImage", path, format, extension)
	ret0, _ := ret[0].(*image.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadImage indicates an expected call of LoadImage
func (mr *MockBookServiceMockRecorder) LoadImage(path, format, extension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadImage", reflect.TypeOf((*MockBookService)(nil).LoadImage), path, format, extension)
}

// SaveImage mocks base method
func (m *MockBookService) SaveImage(path string, image *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveImage", path, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveImage indicates an expected call of SaveImage
func (mr *MockBookServiceMockRecorder) SaveImage(path, image interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveImage", reflect.TypeOf((*MockBookService)(nil).SaveImage), path, image)
}

// UpdateImage mocks base method
func (m *MockBookService) UpdateImage(path string, image *image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImage", path, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateImage indicates an expected call of UpdateImage
func (mr *MockBookServiceMockRecorder) UpdateImage(path, image interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImage", reflect.TypeOf((*MockBookService)(nil).UpdateImage), path, image)
}

// Rate mocks base method
func (m *MockBookService) Rate(UUID string, rating float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rate", UUID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rate indicates an expected call of Rate
func (mr *MockBookServiceMockRecorder) Rate(UUID, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rate", reflect.TypeOf((*MockBookService)(nil).Rate), UUID, rating)
}

// DownloadCountUp mocks base method
func (m *MockBookService) DownloadCountUp(UUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadCountUp", UUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadCountUp indicates an expected call of DownloadCountUp
func (mr *MockBookServiceMockRecorder) DownloadCountUp(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadCountUp", reflect.TypeOf((*MockBookService)(nil).DownloadCountUp), UUID)
}

// MockDirectionService is a mock of DirectionService interface
type MockDirectionService struct {
	ctrl     *gomock.Controller
	recorder *MockDirectionServiceMockRecorder
}

// MockDirectionServiceMockRecorder is the mock recorder for MockDirectionService
type MockDirectionServiceMockRecorder struct {
	mock *MockDirectionService
}

// NewMockDirectionService creates a new mock instance
func NewMockDirectionService(ctrl *gomock.Controller) *MockDirectionService {
	mock := &MockDirectionService{ctrl: ctrl}
	mock.recorder = &MockDirectionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDirectionService) EXPECT() *MockDirectionServiceMockRecorder {
	return m.recorder
}

// GetByUUID mocks base method
func (m *MockDirectionService) GetByUUID(UUID string) (*domain.Direction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", UUID)
	ret0, _ := ret[0].(*domain.Direction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID
func (mr *MockDirectionServiceMockRecorder) GetByUUID(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockDirectionService)(nil).GetByUUID), UUID)
}

// GetAll mocks base method
func (m *MockDirectionService) GetAll(limit, offset int) ([]*domain.Direction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, offset)
	ret0, _ := ret[0].([]*domain.Direction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockDirectionServiceMockRecorder) GetAll(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDirectionService)(nil).GetAll), limit, offset)
}

// Delete mocks base method
func (m *MockDirectionService) Delete(UUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", UUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockDirectionServiceMockRecorder) Delete(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDirectionService)(nil).Delete), UUID)
}

// Create mocks base method
func (m *MockDirectionService) Create(direction *domain.CreateDirectionDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", direction)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockDirectionServiceMockRecorder) Create(direction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDirectionService)(nil).Create), direction)
}

// Update mocks base method
func (m *MockDirectionService) Update(direction *domain.UpdateDirectionDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", direction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockDirectionServiceMockRecorder) Update(direction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDirectionService)(nil).Update), direction)
}

// MockReviewService is a mock of ReviewService interface
type MockReviewService struct {
	ctrl     *gomock.Controller
	recorder *MockReviewServiceMockRecorder
}

// MockReviewServiceMockRecorder is the mock recorder for MockReviewService
type MockReviewServiceMockRecorder struct {
	mock *MockReviewService
}

// NewMockReviewService creates a new mock instance
func NewMockReviewService(ctrl *gomock.Controller) *MockReviewService {
	mock := &MockReviewService{ctrl: ctrl}
	mock.recorder = &MockReviewServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReviewService) EXPECT() *MockReviewServiceMockRecorder {
	return m.recorder
}

// GetByUUID mocks base method
func (m *MockReviewService) GetByUUID(UUID string) (*domain.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", UUID)
	ret0, _ := ret[0].(*domain.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID
func (mr *MockReviewServiceMockRecorder) GetByUUID(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockReviewService)(nil).GetByUUID), UUID)
}

// GetAll mocks base method
func (m *MockReviewService) GetAll(limit, offset int) ([]*domain.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, offset)
	ret0, _ := ret[0].([]*domain.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockReviewServiceMockRecorder) GetAll(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockReviewService)(nil).GetAll), limit, offset)
}

// Delete mocks base method
func (m *MockReviewService) Delete(UUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", UUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockReviewServiceMockRecorder) Delete(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReviewService)(nil).Delete), UUID)
}

// Create mocks base method
func (m *MockReviewService) Create(review *domain.CreateReviewDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", review)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockReviewServiceMockRecorder) Create(review interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReviewService)(nil).Create), review)
}

// Update mocks base method
func (m *MockReviewService) Update(review *domain.UpdateReviewDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", review)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockReviewServiceMockRecorder) Update(review interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReviewService)(nil).Update), review)
}

// Rate mocks base method
func (m *MockReviewService) Rate(UUID string, rating float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rate", UUID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rate indicates an expected call of Rate
func (mr *MockReviewServiceMockRecorder) Rate(UUID, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rate", reflect.TypeOf((*MockReviewService)(nil).Rate), UUID, rating)
}

// MockTagService is a mock of TagService interface
type MockTagService struct {
	ctrl     *gomock.Controller
	recorder *MockTagServiceMockRecorder
}

// MockTagServiceMockRecorder is the mock recorder for MockTagService
type MockTagServiceMockRecorder struct {
	mock *MockTagService
}

// NewMockTagService creates a new mock instance
func NewMockTagService(ctrl *gomock.Controller) *MockTagService {
	mock := &MockTagService{ctrl: ctrl}
	mock.recorder = &MockTagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTagService) EXPECT() *MockTagServiceMockRecorder {
	return m.recorder
}

// GetByUUID mocks base method
func (m *MockTagService) GetByUUID(UUID string) (*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", UUID)
	ret0, _ := ret[0].(*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID
func (mr *MockTagServiceMockRecorder) GetByUUID(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockTagService)(nil).GetByUUID), UUID)
}

// GetManyByUUIDs mocks base method
func (m *MockTagService) GetManyByUUIDs(UUIDs []string) ([]*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManyByUUIDs", UUIDs)
	ret0, _ := ret[0].([]*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManyByUUIDs indicates an expected call of GetManyByUUIDs
func (mr *MockTagServiceMockRecorder) GetManyByUUIDs(UUIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyByUUIDs", reflect.TypeOf((*MockTagService)(nil).GetManyByUUIDs), UUIDs)
}

// GetAll mocks base method
func (m *MockTagService) GetAll(limit, offset int) ([]*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, offset)
	ret0, _ := ret[0].([]*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockTagServiceMockRecorder) GetAll(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTagService)(nil).GetAll), limit, offset)
}

// Delete mocks base method
func (m *MockTagService) Delete(UUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", UUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockTagServiceMockRecorder) Delete(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagService)(nil).Delete), UUID)
}

// Create mocks base method
func (m *MockTagService) Create(tag *domain.CreateTagDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tag)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockTagServiceMockRecorder) Create(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagService)(nil).Create), tag)
}

// Update mocks base method
func (m *MockTagService) Update(tag *domain.UpdateTagDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockTagServiceMockRecorder) Update(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTagService)(nil).Update), tag)
}

// MockVideoService is a mock of VideoService interface
type MockVideoService struct {
	ctrl     *gomock.Controller
	recorder *MockVideoServiceMockRecorder
}

// MockVideoServiceMockRecorder is the mock recorder for MockVideoService
type MockVideoServiceMockRecorder struct {
	mock *MockVideoService
}

// NewMockVideoService creates a new mock instance
func NewMockVideoService(ctrl *gomock.Controller) *MockVideoService {
	mock := &MockVideoService{ctrl: ctrl}
	mock.recorder = &MockVideoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockVideoService) EXPECT() *MockVideoServiceMockRecorder {
	return m.recorder
}

// GetByUUID mocks base method
func (m *MockVideoService) GetByUUID(UUID string) (*domain.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", UUID)
	ret0, _ := ret[0].(*domain.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID
func (mr *MockVideoServiceMockRecorder) GetByUUID(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockVideoService)(nil).GetByUUID), UUID)
}

// GetAll mocks base method
func (m *MockVideoService) GetAll(sortingOptions *domain.SortFilterPagination) ([]*domain.Video, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", sortingOptions)
	ret0, _ := ret[0].([]*domain.Video)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll
func (mr *MockVideoServiceMockRecorder) GetAll(sortingOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockVideoService)(nil).GetAll), sortingOptions)
}

// Delete mocks base method
func (m *MockVideoService) Delete(UUID, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", UUID, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockVideoServiceMockRecorder) Delete(UUID, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVideoService)(nil).Delete), UUID, path)
}

// Create mocks base method
func (m *MockVideoService) Create(video *domain.CreateVideoDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", video)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockVideoServiceMockRecorder) Create(video interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVideoService)(nil).Create), video)
}

// Update mocks base method
func (m *MockVideoService) Update(video *domain.UpdateVideoDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", video)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockVideoServiceMockRecorder) Update(video interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVideoService)(nil).Update), video)
}

// LoadFile mocks base method
func (m *MockVideoService) LoadFile(path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFile", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadFile indicates an expected call of LoadFile
func (mr *MockVideoServiceMockRecorder) LoadFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFile", reflect.TypeOf((*MockVideoService)(nil).LoadFile), path)
}

// SaveFile mocks base method
func (m *MockVideoService) SaveFile(path, fileName string, file io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", path, fileName, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFile indicates an expected call of SaveFile
func (mr *MockVideoServiceMockRecorder) SaveFile(path, fileName, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockVideoService)(nil).SaveFile), path, fileName, file)
}

// UpdateFile mocks base method
func (m *MockVideoService) UpdateFile(dto *domain.UpdateVideoFileDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFile", dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFile indicates an expected call of UpdateFile
func (mr *MockVideoServiceMockRecorder) UpdateFile(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockVideoService)(nil).UpdateFile), dto)
}

// Rate mocks base method
func (m *MockVideoService) Rate(UUID string, rating float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rate", UUID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rate indicates an expected call of Rate
func (mr *MockVideoServiceMockRecorder) Rate(UUID, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rate", reflect.TypeOf((*MockVideoService)(nil).Rate), UUID, rating)
}

// DownloadCountUp mocks base method
func (m *MockVideoService) DownloadCountUp(UUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadCountUp", UUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadCountUp indicates an expected call of DownloadCountUp
func (mr *MockVideoServiceMockRecorder) DownloadCountUp(UUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadCountUp", reflect.TypeOf((*MockVideoService)(nil).DownloadCountUp), UUID)
}
