DROP TABLE author CASCADE;
DROP TABLE direction CASCADE;
DROP TABLE tag CASCADE;
DROP TABLE audio CASCADE;
DROP TABLE video CASCADE;
DROP TABLE article CASCADE;
DROP TABLE book CASCADE;
DROP TABLE review CASCADE;

DROP TYPE  difficulty CASCADE;
DROP TYPE  review_source CASCADE;