FROM golang:1.18-alpine

RUN go version
ENV GOPATH=/

# Set destination for COPY
WORKDIR /library

# build go app
COPY ["go.mod", "go.sum", "./"]
RUN go mod download

COPY ./ ./

RUN go build -o library ./cmd/main.go

CMD [ "./library" ]